; Taille maximale d'un fichier téléchargé
upload_max_filesize = 32M

; Taille maximale des données POST
post_max_size = 32M

memory_limit = 256M

; Temps d'exécution maximum d'un script
max_execution_time = 300

; Temps maximum d'attente pour un script
max_input_time = 300
